export const CODEMIRROR_PACKAGES = [
	'@codemirror/autocomplete',
	'@codemirror/commands',
	'@codemirror/lang-cpp',
	'@codemirror/lang-css',
	'@codemirror/lang-html',
	'@codemirror/lang-java',
	'@codemirror/lang-javascript',
	'@codemirror/lang-json',
	'@codemirror/lang-markdown',
	'@codemirror/lang-php',
	'@codemirror/lang-python',
	'@codemirror/lang-rust',
	'@codemirror/lang-sql',
	'@codemirror/lang-xml',
	'@codemirror/language',
	'@codemirror/lint',
	'@codemirror/merge',
	'@codemirror/state',
	'@codemirror/theme-one-dark',
	'@codemirror/view',
] as const;
